'use client';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, House, Leaf, Ruler, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';

const references = [
 {src:'/generated/design-references/realistic-local-01.webp',title:'Contemporary Elegance',copy:'Warm timber, stone textures and layered lighting for a premium family home.'},
 {src:'/generated/design-references/realistic-local-02.webp',title:'Modern Minimalist',copy:'Clean geometry, generous glazing and a calm contemporary facade.'},
 {src:'/generated/design-references/realistic-local-03.webp',title:'Architectural Harmony',copy:'Balanced volumes, landscaped edges and refined exterior detailing.'},
];

export function HomeDesignShowcase(){
 const [index,setIndex]=useState(0);
 useEffect(()=>{const timer=window.setInterval(()=>setIndex(i=>(i+1)%references.length),6500);return()=>window.clearInterval(timer)},[]);
 const panels=[references[index],references[(index+1)%references.length],references[(index+2)%references.length],references[(index+3)%references.length]];
 const go=(n:number)=>setIndex((n+references.length)%references.length);
 return <>
  <section className="relative overflow-hidden bg-[#08121f] text-white"><div className="grid min-h-[520px] grid-cols-1 md:grid-cols-4">{panels.map((p,i)=><div key={`${p.src}-${i}`} className="relative min-h-[340px] overflow-hidden border-b border-white/10 md:min-h-[520px] md:border-b-0 md:border-r last:md:border-r-0"><img src={p.src} alt={p.title} loading={i===0?'eager':'lazy'} decoding="async" className="h-full min-h-[340px] w-full object-cover md:min-h-[520px]"/><div className="absolute inset-0 bg-gradient-to-t from-[#08121f]/85 via-transparent to-[#08121f]/10"/>{i===0&&<div className="absolute inset-0 flex items-end p-7 sm:p-10 lg:p-12"><div className="max-w-md"><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-4 py-2 text-xs font-semibold uppercase tracking-[0.18em] backdrop-blur-sm"><Sparkles className="h-4 w-4 text-primary"/> Design inspiration</div><h1 className="display-title text-4xl leading-[1.02] text-white sm:text-5xl lg:text-6xl">Designing Spaces.<span className="block text-white/85">Building Dreams.</span></h1><p className="mt-5 max-w-sm text-sm leading-7 text-white/70 sm:text-base">Original architectural references to help you choose a facade, mood and level of detail for your home.</p><Button asChild className="mt-7 rounded-xl bg-primary font-bold text-[#08121f] hover:bg-primary/90"><Link href="/design-reference">View design references <ArrowRight className="ml-2 h-4 w-4"/></Link></Button></div></div>}</div>)}</div><button type="button" onClick={()=>go(index-1)} aria-label="Previous design inspiration" className="absolute left-4 top-1/2 z-10 -translate-y-1/2 inline-flex h-11 w-11 items-center justify-center rounded-full border border-white/25 bg-black/30 text-white backdrop-blur-sm transition hover:border-primary hover:text-primary sm:left-7"><ArrowLeft className="h-5 w-5"/></button><button type="button" onClick={()=>go(index+1)} aria-label="Next design inspiration" className="absolute right-4 top-1/2 z-10 -translate-y-1/2 inline-flex h-11 w-11 items-center justify-center rounded-full border border-white/25 bg-black/30 text-white backdrop-blur-sm transition hover:border-primary hover:text-primary sm:right-7"><ArrowRight className="h-5 w-5"/></button><div className="absolute bottom-5 left-1/2 z-10 flex -translate-x-1/2 gap-2 rounded-full border border-white/10 bg-black/20 px-3 py-2 backdrop-blur-sm">{references.map((r,d)=><button key={r.src} type="button" onClick={()=>setIndex(d)} aria-label={`Show ${r.title}`} className={`h-2.5 rounded-full transition-all ${d===index?'w-8 bg-primary':'w-2.5 bg-white/60'}`}/>)}</div></section>
  <section className="bg-background py-20 md:py-24"><div className="section-shell"><div className="grid gap-10 lg:grid-cols-[0.95fr_1.05fr] lg:items-start lg:gap-16"><div><p className="eyebrow">Design inspiration</p><h2 className="display-title mt-4 text-4xl sm:text-5xl">House design ideas to inspire you.</h2><p className="mt-5 max-w-xl text-base leading-8 text-muted-foreground">Explore original residential visual references before we shape a practical brief around your site, budget and lifestyle.</p><Button asChild className="mt-7 rounded-xl bg-[#08121f] font-semibold text-white hover:bg-[#122236]"><Link href="/design-reference">View all references <ArrowRight className="ml-2 h-4 w-4"/></Link></Button></div><div className="grid gap-5 sm:grid-cols-3">{[['Modern facades','Contemporary & elegant architectural styles',House],['Smart spaces','Thoughtful layouts for comfortable living',Ruler],['Premium materials','Quality finishes chosen for long-term appeal',Leaf]].map(([t,c,Icon])=><div key={String(t)} className="border-l border-border pl-5 first:border-l-0 first:pl-0 sm:first:border-l sm:first:pl-5"><Icon className="h-6 w-6 text-primary"/><h3 className="mt-4 text-sm font-bold">{t}</h3><p className="mt-2 text-xs leading-5 text-muted-foreground">{c}</p></div>)}</div></div><div className="mt-12 grid gap-4 sm:grid-cols-3">{references.map(r=><Link key={r.src} href="/design-reference" className="group relative overflow-hidden rounded-2xl border bg-[#08121f] shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="aspect-[4/3] overflow-hidden"><img src={r.src} alt={r.title} loading="lazy" decoding="async" className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.03]"/><div className="absolute inset-0 bg-gradient-to-t from-black/75 via-transparent to-transparent"/></div><div className="absolute inset-x-0 bottom-0 p-5 text-white"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-primary">Reference concept</p><h3 className="mt-2 text-lg font-semibold">{r.title}</h3><p className="mt-1 text-sm text-white/70">{r.copy}</p></div></Link>)}</div></div></section>
 </>;
}
